base:
  base_dir: '../runs-st/'
  experiment: 'train_part'
dataset:
  pth : '/home1/quanquan/datasets/Cephalometric/'

training:
  batch_size : 16
  num_workers : 8
  num_landmarks : 19
  learning_rate : 0.0003
  decay_step : 150
  decay_gamma : 0.1
  num_epochs : 400
  save_seq : 10
  lambda : 2