base:
  base_dir: "/home1/quanquan/code/landmark/code/runs/self_train/"
  experiment: 'self_train_handx'
  tag: ''
  stage: ''
logger:
  mode: ['tb', ]

dataset:
  name: 'Cephalometric'
  pth: '/home1/quanquan/datasets/hand/hand/jpg'
  label_path: '/home1/quanquan/datasets/hand/hand/all.csv'
  n_cls: 37

special:
  emb_len: 128
  regress: true  # Regression module
  non_local: false

training:
  gpus: ''
  ddp:
    master_addr: 'localhost'
    master_port: '25709'
  batch_size : 2
  num_workers : 8
  num_epochs : 100  # epochs
  use_amp: false
  save_interval : 10
  val_check_interval: 10
  decay_step: 50
  decay_gamma: 0.8
  lambda: 2
  lr: 0.0001
  weight_decay: 0.0001
  indices:
